LANGUAGE_STRINGS = {
    "English": {
        "welcome_message": "Welcome! Please provide your details to begin your consultation.",
        "full_name": "👤 Full Name",
        "age": "🎂 Age",
        "email_address": "📧 Email Address",
        "preferred_language": "🗣️ Preferred Language",
        "start_session": "Start Session",
        "setting_up_session": "Setting up your session...",
        "consultation_welcome": "Welcome, {name}! Let's begin.",
        "symptoms_question": "1. How are you feeling today?",
        "describe_symptoms": "Describe your current symptoms (Text or Voice):",
        "upload_voice_recording": "Or upload a voice recording (MP3, WAV)",
        "voice_input_received": "Voice input received. Transcription functionality will be implemented soon.",
        "past_history_question": "2. What is your past medical history?",
        "select_conditions": "Select any pre-existing conditions:",
        "recent_report_question": "3. Do you have a recent medical report?",
        "upload_report": "Upload report (PDF or Image)",
        "submit_for_analysis": "Submit for Analysis",
        "processing_info": "Processing your information...",
        "final_triage_results": "Final Triage Results",
        "running_ai_analysis": "Running AI analysis... Please wait.",
        "overall_assessment": "Overall Assessment:",
        "recommended_next_steps": "Recommended Next Steps",
        "seek_immediate_attention": "Please seek immediate medical attention.",
        "consult_doctor_24_hours": "We recommend consulting a doctor within 24 hours.",
        "home_care_sufficient": "Home care may be sufficient. Monitor your symptoms.",
        "view_analysis_details": "View Analysis Details",
        "possible_disease": "Possible Disease:",
        "ai_reasoning": "AI Reasoning:",
        "extracted_report_data": "Extracted Report Data:",
        "report_explanation": "Report Explanation:",
        "dietary_recommendations": "Dietary Recommendations:",
        "top_5_similar_cases": "Top 5 Similar Past Cases:",
        "your_health_passport": "Your Health Passport",
        "download_summary": "Download a complete summary of this consultation for your records or to share with a doctor.",
        "download_pdf_summary": "Download PDF Summary",
        "start_new_consultation": "Start New Consultation",
        "logout": "Logout",
        "database_connection_error": "Could not connect to the database. Please check your MongoDB connection and try again.",
        "chatbot_more_questions": "A Few More Questions...",
        "chatbot_info_message": "To provide you with the most accurate assessment, please answer a few clarifying questions.",
        "regarding": "Regarding",
        "submit_answers": "Submit Answers",
        "processing_report": "Processing report...",
        "report_processed_success": "Report processed successfully!",
        "please_upload_report": "Please upload a medical report to proceed.",
        "ask_previous_issues": "Do you have any previous health issues?",
        "ask_common_conditions": "Have you ever had {conditions_list}?",
        "confirm_past_history": "We found your past health history — {history_list}. Is this still accurate?",
        "confirm_update_history": "Confirm/Update History",
        "no_skip_report": "No, skip report"
    },
    "Marathi": {
        "welcome_message": "स्वागत आहे! सल्ला सुरू करण्यासाठी कृपया तुमचे तपशील द्या.",
        "full_name": "👤 पूर्ण नाव",
        "age": "🎂 वय",
        "email_address": "📧 ईमेल पत्ता",
        "preferred_language": "🗣️ पसंतीची भाषा",
        "start_session": "सत्र सुरू करा",
        "setting_up_session": "तुमचे सत्र सेट करत आहे...",
        "consultation_welcome": "स्वागत आहे, {name}! चला सुरू करूया.",
        "symptoms_question": "1. आज तुम्हाला कसे वाटत आहे?",
        "describe_symptoms": "तुमची सध्याची लक्षणे वर्णन करा (मजकूर किंवा आवाज):",
        "upload_voice_recording": "किंवा आवाज रेकॉर्डिंग अपलोड करा (MP3, WAV)",
        "voice_input_received": "आवाज इनपुट प्राप्त झाले आहे. ट्रान्सक्रिप्शन कार्यक्षमता लवकरच लागू केली जाईल.",
        "past_history_question": "2. तुमचा मागील वैद्यकीय इतिहास काय आहे?",
        "select_conditions": "कोणत्याही पूर्वनिविष्ठ स्थिती निवडा:",
        "recent_report_question": "3. तुमच्याकडे अलीकडील वैद्यकीय अहवाल आहे का?",
        "upload_report": "अहवाल अपलोड करा (PDF किंवा प्रतिमा)",
        "submit_for_analysis": "विश्लेषणासाठी सबमिट करा",
        "processing_info": "तुमची माहिती प्रक्रिया करत आहे...",
        "final_triage_results": "अंतिम वर्गीकरण परिणाम",
        "running_ai_analysis": "एआय विश्लेषण चालवत आहे... कृपया थांबा.",
        "overall_assessment": "एकूण मूल्यांकन:",
        "recommended_next_steps": "शिफारस केलेले पुढील पाऊले",
        "seek_immediate_attention": "कृपया त्वरित वैद्यकीय मदत घ्या.",
        "consult_doctor_24_hours": "आम्ही 24 तासांच्या आत डॉक्टरांचा सल्ला घेण्याची शिफारस करतो.",
        "home_care_sufficient": "घरगुती काळजी पुरेशी असू शकते. तुमच्या लक्षणांवर लक्ष ठेवा.",
        "view_analysis_details": "विश्लेषण तपशील पहा",
        "possible_disease": "संभाव्य रोग:",
        "ai_reasoning": "एआय तर्क:",
        "extracted_report_data": "काढलेला अहवाल डेटा:",
        "report_explanation": "अहवाल स्पष्टीकरण:",
        "dietary_recommendations": "आहाराच्या शिफारसी:",
        "top_5_similar_cases": "शीर्ष 5 समान मागील प्रकरणे:",
        "your_health_passport": "तुमचा आरोग्य पासपोर्ट",
        "download_summary": "तुमच्या नोंदींसाठी किंवा डॉक्टरांसोबत शेअर करण्यासाठी या सल्लामसलतचा संपूर्ण सारांश डाउनलोड करा.",
        "download_pdf_summary": "पीडीएफ सारांश डाउनलोड करा",
        "start_new_consultation": "नवीन सल्ला सुरू करा",
        "logout": "लॉगआउट",
        "database_connection_error": "डेटाबेसशी कनेक्ट होऊ शकले नाही. कृपया तुमचे MongoDB कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.",
        "chatbot_more_questions": "आणखी काही प्रश्न...",
        "chatbot_info_message": "तुम्हाला सर्वात अचूक मूल्यांकन देण्यासाठी, कृपया काही स्पष्टीकरणात्मक प्रश्नांची उत्तरे द्या.",
        "regarding": "संदर्भात",
        "submit_answers": "उत्तरे सबमिट करा",
        "processing_report": "अहवाल प्रक्रिया करत आहे...",
        "report_processed_success": "अहवाल यशस्वीरित्या प्रक्रिया केला!",
        "please_upload_report": "कृपया पुढे जाण्यासाठी वैद्यकीय अहवाल अपलोड करा.",
        "ask_previous_issues": "तुम्हाला यापूर्वी काही आरोग्य समस्या आहेत का?",
        "ask_common_conditions": "तुम्हाला कधी {conditions_list} झाले आहे का?",
        "confirm_past_history": "आम्हाला तुमचा मागील आरोग्य इतिहास — {history_list} आढळला. हे अजूनही अचूक आहे का?",
        "confirm_update_history": "इतिहास निश्चित/अद्यतनित करा",
        "no_skip_report": "नाही, अहवाल वगळा"
    }
    # Add more languages as needed
}
