LANGUAGE_STRINGS = {
    "English": {
        "welcome_message": "Welcome to AI Health Triage. This system helps assess your health concerns and provides guidance.",
        "full_name": "Full Name",
        "age": "Age",
        "email_address": "Email Address",
        "preferred_language": "Preferred Language",
        "start_session": "Start Health Assessment",
        "setting_up_session": "Setting up your session...",
        "database_connection_error": "Unable to connect to database. Please try again.",
        "consultation_welcome": "Welcome {name}! Let's assess your health concerns.",
        "symptoms_question": "Please describe your current symptoms or health concerns:",
        "describe_symptoms": "Describe what you're feeling (e.g., fever, headache, stomach pain, weakness)",
        "upload_voice_recording": "Upload Voice Recording (.mp3, .wav)",
        "voice_input_received": "Voice recording received. Processing...",
        "upload_report": "Upload Medical Report (PDF, Image)",
        "processing_report": "Processing your medical report...",
        "report_processed_success": "Report processed successfully!",
        "please_upload_report": "Please upload a medical report to continue.",
        "submit_for_analysis": "Submit for Analysis",
        "past_history_question": "Medical History Information",
        "ask_previous_issues": "Do you have any ongoing medical conditions or past health issues?",
        "ask_common_conditions": "Please select any conditions that apply to you:",
        "confirm_past_history": "We found your previous medical history: {history_list}. Please update if needed:",
        "select_conditions": "Select your medical conditions:",
        "confirm_update_history": "Confirm & Update History",
        "recent_report_question": "Do you have any recent medical reports to upload?",
        "no_skip_report": "Skip - No Report",
        "final_triage_results": "Your Health Assessment Results",
        "running_ai_analysis": "Analyzing your symptoms and health data...",
        "overall_assessment": "Overall Health Risk Assessment:",
        "recommended_next_steps": "Recommended Next Steps:",
        "seek_immediate_attention": "URGENT: Seek immediate medical attention at the nearest hospital",
        "consult_doctor_24_hours": "IMPORTANT: Consult a doctor within 24 hours",
        "home_care_sufficient": "Your symptoms suggest home care may be sufficient with monitoring",
        "view_analysis_details": "View Detailed Analysis",
        "possible_disease": "Most Likely Condition:",
        "ai_reasoning": "Medical Reasoning:",
        "extracted_report_data": "Your Report Findings:",
        "report_explanation": "Report Explanation:",
        "dietary_recommendations": "Dietary Suggestions:",
        "top_5_similar_cases": "Similar Cases from Medical Database:",
        "your_health_passport": "Your Health Summary",
        "download_summary": "Download a complete summary of this consultation for your records or to share with a doctor.",
        "download_pdf_summary": "Download PDF Health Summary",
        "start_new_consultation": "Start New Health Assessment",
        "logout": "Logout",
        "chatbot_more_questions": "Additional Health Questions",
        "chatbot_info_message": "Based on your symptoms, I need to ask a few more specific questions for better assessment.",
        "regarding": "Regarding",
        "submit_answers": "Submit Answers"
    },
    
    "Hindi": {
        "welcome_message": "AI स्वास्थ्य ट्रायज में आपका स्वागत है। यह सिस्टम आपकी स्वास्थ्य चिंताओं का आकलन करता है।",
        "full_name": "पूरा नाम",
        "age": "उम्र",
        "email_address": "ईमेल पता",
        "preferred_language": "पसंदीदा भाषा",
        "start_session": "स्वास्थ्य जांच शुरू करें",
        "setting_up_session": "आपका सेशन तैयार कर रहे हैं...",
        "database_connection_error": "डेटाबेस से कनेक्ट नहीं हो सका। कृपया फिर से कोशिश करें।",
        "consultation_welcome": "स्वागत है {name}! आइए आपकी स्वास्थ्य समस्याओं का आकलन करते हैं।",
        "symptoms_question": "कृपया अपने वर्तमान लक्षण या स्वास्थ्य समस्याओं का वर्णन करें:",
        "describe_symptoms": "बताएं कि आप कैसा महसूस कर रहे हैं (जैसे बुखार, सिर दर्द, पेट दर्द, कमजोरी)",
        "upload_voice_recording": "वॉयस रिकॉर्डिंग अपलोड करें (.mp3, .wav)",
        "voice_input_received": "वॉयस रिकॉर्डिंग प्राप्त हुई। प्रोसेसिंग...",
        "upload_report": "मेडिकल रिपोर्ट अपलोड करें (PDF, Image)",
        "processing_report": "आपकी मेडिकल रिपोर्ट प्रोसेस कर रहे हैं...",
        "report_processed_success": "रिपोर्ट सफलतापूर्वक प्रोसेस हुई!",
        "please_upload_report": "कृपया आगे बढ़ने के लिए मेडिकल रिपोर्ट अपलोड करें।",
        "submit_for_analysis": "विश्लेषण के लिए जमा करें",
        "past_history_question": "चिकित्सा इतिहास की जानकारी",
        "ask_previous_issues": "क्या आपको कोई चल रही चिकित्सा समस्या या पुरानी स्वास्थ्य समस्याएं हैं?",
        "ask_common_conditions": "कृपया कोई भी समस्या चुनें जो आप पर लागू होती हो:",
        "confirm_past_history": "हमें आपका पिछला चिकित्सा इतिहास मिला: {history_list}। यदि आवश्यक हो तो कृपया अपडेट करें:",
        "select_conditions": "अपनी चिकित्सा समस्याएं चुनें:",
        "confirm_update_history": "पुष्टि करें और इतिहास अपडेट करें",
        "recent_report_question": "क्या आपके पास अपलोड करने के लिए कोई हाल की मेडिकल रिपोर्ट है?",
        "no_skip_report": "छोड़ें - कोई रिपोर्ट नहीं",
        "final_triage_results": "आपके स्वास्थ्य मूल्यांकन के परिणाम",
        "running_ai_analysis": "आपके लक्षणों और स्वास्थ्य डेटा का विश्लेषण कर रहे हैं...",
        "overall_assessment": "समग्र स्वास्थ्य जोखिम मूल्यांकन:",
        "recommended_next_steps": "सुझाए गए अगले कदम:",
        "seek_immediate_attention": "तुरंत: नजदीकी अस्पताल में तुरंत चिकित्सा सहायता लें",
        "consult_doctor_24_hours": "महत्वपूर्ण: 24 घंटे के भीतर डॉक्टर से सलाह लें",
        "home_care_sufficient": "आपके लक्षण घरेलू देखभाल के साथ निगरानी पर्याप्त हो सकती है",
        "view_analysis_details": "विस्तृत विश्लेषण देखें",
        "possible_disease": "संभावित स्थिति:",
        "ai_reasoning": "चिकित्सा तर्क:",
        "extracted_report_data": "आपकी रिपोर्ट के निष्कर्ष:",
        "report_explanation": "रिपोर्ट की व्याख्या:",
        "dietary_recommendations": "आहार सुझाव:",
        "top_5_similar_cases": "चिकित्सा डेटाबेस से समान मामले:",
        "your_health_passport": "आपका स्वास्थ्य सारांश",
        "download_summary": "इस परामर्श का पूरा सारांश डाउनलोड करें।",
        "download_pdf_summary": "PDF स्वास्थ्य सारांश डाउनलोड करें",
        "start_new_consultation": "नया स्वास्थ्य मूल्यांकन शुरू करें",
        "logout": "लॉग आउट",
        "chatbot_more_questions": "अतिरिक्त स्वास्थ्य प्रश्न",
        "chatbot_info_message": "आपके लक्षणों के आधार पर, बेहतर मूल्यांकन के लिए मुझे कुछ और विशिष्ट प्रश्न पूछने होंगे।",
        "regarding": "के संबंध में",
        "submit_answers": "उत्तर जमा करें"
    },
    
    "Marathi": {
        "welcome_message": "AI आरोग्य ट्रायजमध्ये आपले स्वागत आहे. ही प्रणाली आपल्या आरोग्य चिंतांचे मूल्यांकन करते.",
        "full_name": "पूर्ण नाव",
        "age": "वय",
        "email_address": "ईमेल पत्ता",
        "preferred_language": "प्राधान्य भाषा",
        "start_session": "आरोग्य तपासणी सुरू करा",
        "setting_up_session": "आपले सेशन तयार करत आहोत...",
        "database_connection_error": "डेटाबेससशी कनेक्ट होऊ शकत नाही. कृपया पुन्हा प्रयत्न करा.",
        "consultation_welcome": "स्वागत आहे {name}! आपल्या आरोग्य समस्यांचे मूल्यांकन करूया.",
        "symptoms_question": "कृपया आपली सध्याची लक्षणे किंवा आरोग्य समस्यांचे वर्णन करा:",
        "describe_symptoms": "आपल्याला कसे वाटत आहे ते सांगा (उदा. ताप, डोकेदुखी, पोटदुखी, अशक्तपणा)",
        "upload_voice_recording": "व्हॉईस रेकॉर्डिंग अपलोड करा (.mp3, .wav)",
        "voice_input_received": "व्हॉईस रेकॉर्डिंग मिळाली. प्रक्रिया करत आहोत...",
        "upload_report": "वैद्यकीय अहवाल अपलोड करा (PDF, Image)",
        "processing_report": "आपला वैद्यकीय अहवाल प्रक्रिया करत आहोत...",
        "report_processed_success": "अहवाल यशस्वीरीत्या प्रक्रिया झाला!",
        "please_upload_report": "कृपया पुढे जाण्यासाठी वैद्यकीय अहवाल अपलोड करा.",
        "submit_for_analysis": "विश्लेषणासाठी सबमिट करा",
        "past_history_question": "वैद्यकीय इतिहासाची माहिती",
        "ask_previous_issues": "आपल्याला काही चालू वैद्यकीय समस्या किंवा जुन्या आरोग्य समस्या आहेत का?",
        "ask_common_conditions": "कृपया आपल्यावर लागू होणाऱ्या कोणत्याही समस्या निवडा:",
        "confirm_past_history": "आम्हाला आपला मागील वैद्यकीय इतिहास सापडला: {history_list}. आवश्यक असल्यास कृपया अपडेट करा:",
        "select_conditions": "आपल्या वैद्यकीय समस्या निवडा:",
        "confirm_update_history": "पुष्टी करा आणि इतिहास अपडेट करा",
        "recent_report_question": "आपल्याकडे अपलोड करण्यासाठी कोणते अलीकडील वैद्यकीय अहवाल आहेत का?",
        "no_skip_report": "वगळा - कोणताही अहवाल नाही",
        "final_triage_results": "आपल्या आरोग्य मूल्यांकनाचे परिणाम",
        "running_ai_analysis": "आपली लक्षणे आणि आरोग्य डेटाचे विश्लेषण करत आहोत...",
        "overall_assessment": "एकूण आरोग्य जोखीम मूल्यांकन:",
        "recommended_next_steps": "सुचवलेली पुढील पायऱ्या:",
        "seek_immediate_attention": "तातडीची: जवळच्या रुग्णालयात तातडीने वैद्यकीय मदत घ्या",
        "consult_doctor_24_hours": "महत्त्वाचे: 24 तासांत डॉक्टरांचा सल्ला घ्या",
        "home_care_sufficient": "आपली लक्षणे घरगुती काळजीसह निरीक्षण पुरेसे असू शकते",
        "view_analysis_details": "तपशीलवार विश्लेषण पहा",
        "possible_disease": "संभाव्य स्थिती:",
        "ai_reasoning": "वैद्यकीय तर्क:",
        "extracted_report_data": "आपल्या अहवालातील निष्कर्ष:",
        "report_explanation": "अहवालाचे स्पष्टीकरण:",
        "dietary_recommendations": "आहार सूचना:",
        "top_5_similar_cases": "वैद्यकीय डेटाबेसकडून समान प्रकरणे:",
        "your_health_passport": "आपला आरोग्य सारांश",
        "download_summary": "या सल्लामसलतीचा संपूर्ण सारांश डाउनलोड करा.",
        "download_pdf_summary": "PDF आरोग्य सारांश डाउनलोड करा",
        "start_new_consultation": "नवीन आरोग्य मूल्यांकन सुरू करा",
        "logout": "लॉग आउट",
        "chatbot_more_questions": "अतिरिक्त आरोग्य प्रश्न",
        "chatbot_info_message": "आपल्या लक्षणांच्या आधारे, चांगल्या मूल्यांकनासाठी मला काही अधिक विशिष्ट प्रश्न विचारावे लागतील.",
        "regarding": "संबंधित",
        "submit_answers": "उत्तरे सबमिट करा"
    }
}
